    rvm:           # перечень всех версий Ruby, на которых хотите протестировать
      - ree
      - 1.8.7
      - 1.9.2
      - jruby
      - rbx
    script: "bundle exec rspec spec/*&&cd modular-app&&bundle exec rake spec"
